[project]
name = "tarea2-rl-qlearning"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "gymnasium[toy-text]>=1.1.1",
    "numpy>=2.3.0",
]
